import { type AppType } from 'next/dist/shared/lib/utils'
import '../styles/globals.css'
import {
  Container,
  createTheme,
  NextUIProvider,
  Spacer,
} from '@nextui-org/react'
import { ThemeProvider as NextThemesProvider } from 'next-themes'
import Hero from '../components/Hero'
import Navigation from '../components/Navigation'
import Head from 'next/head'
import Box from '../components/Box'

const lightTheme = createTheme({
  type: 'light',
})

const darkTheme = createTheme({
  type: 'dark',
})

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <NextThemesProvider
      defaultTheme="system"
      attribute="class"
      value={{
        light: lightTheme.className,
        dark: darkTheme.className,
      }}
    >
      <NextUIProvider>
        <Head>
          <title>IETI</title>
          <meta name="description" content="Generated by create-t3-app" />
        </Head>
        <Box
          css={{
            flexDirection: 'column',
            minHeight: '100vh',
          }}
        >
          <Navigation />
          <Spacer />

          <Container
            as="main"
            display="flex"
            direction="column"
            css={{
              flexGrow: 1,
            }}
          >
            <Hero />
            <Component {...pageProps} />
          </Container>
        </Box>
      </NextUIProvider>
    </NextThemesProvider>
  )
}

export default MyApp
